Fix app crash when no referral problem selected
OpenSRP/opensrp-client-chw-referral pull request #22
Opened 2020-02-14 11:18 UTC by ellykits

2020-02-14 15:51 UTC, cozej4 submitted a review, later dismissed

2020-02-17 12:55 UTC, dubdabasoduba requested changes

2020-02-17 12:55 UTC, dubdabasoduba commented on opensrp-chw-referral/src/main/java/org/smartregister/chw/referral/interactor/BaseIssueReferralInteractor.kt
> +        val hasProblems = extractReferralProblems != null && extractReferralProblems.isNotEmpty()
Please use the `StringUtils.isNotBlank()` instead

2020-02-17 12:55 UTC, dubdabasoduba commented on opensrp-chw-referral/src/main/java/org/smartregister/chw/referral/interactor/BaseIssueReferralInteractor.kt
> +                    (valuesHashMap["chw_referral_hf"]?.value as NFormViewData?)?.metadata?.get("openmrs_entity_id")
Move these hardcoded strings to the constants file

2020-02-17 13:21 UTC, cozej4 submitted a review, later dismissed

2020-02-17 13:39 UTC, dubdabasoduba approved these changes

2020-02-17 13:41 UTC, merged